GET  http://localhost:5234/api/user

###

//just for testing
POST  http://localhost:5234/api/auth/register/user
Content-Type: application/json

{
  "name": "valentin",
  "email": "well@gmail.com",
  "password": "hello"
}
//